/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PackedDoubleEndedQueue,
  PackedDoubleEndedQueueInterface,
} from "../PackedDoubleEndedQueue";

const _abi = [
  {
    inputs: [],
    name: "InvalidSlot",
    type: "error",
  },
  {
    inputs: [],
    name: "QueueEmpty",
    type: "error",
  },
  {
    inputs: [],
    name: "QueueFull",
    type: "error",
  },
  {
    inputs: [],
    name: "QueueOutOfBounds",
    type: "error",
  },
];

const _bytecode =
  "0x602d6037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea164736f6c6343000814000a";

export class PackedDoubleEndedQueue__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PackedDoubleEndedQueue> {
    return super.deploy(overrides || {}) as Promise<PackedDoubleEndedQueue>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PackedDoubleEndedQueue {
    return super.attach(address) as PackedDoubleEndedQueue;
  }
  connect(signer: Signer): PackedDoubleEndedQueue__factory {
    return super.connect(signer) as PackedDoubleEndedQueue__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PackedDoubleEndedQueueInterface {
    return new utils.Interface(_abi) as PackedDoubleEndedQueueInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PackedDoubleEndedQueue {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PackedDoubleEndedQueue;
  }
}
