/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IVaultFactoryInterface extends ethers.utils.Interface {
  functions: {
    "getBlackHoleAddress()": FunctionFragment;
    "getCurrentFeePercentage()": FunctionFragment;
    "getCurrentProjectVaultFeePercentage()": FunctionFragment;
    "getFeeRecieverAddress()": FunctionFragment;
    "getProjectVaultAddress()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBlackHoleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentProjectVaultFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeRecieverAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectVaultAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getBlackHoleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentProjectVaultFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeRecieverAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectVaultAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class IVaultFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IVaultFactoryInterface;

  functions: {
    getBlackHoleAddress(overrides?: CallOverrides): Promise<[string]>;

    getCurrentFeePercentage(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getCurrentProjectVaultFeePercentage(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getFeeRecieverAddress(overrides?: CallOverrides): Promise<[string]>;

    getProjectVaultAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  getBlackHoleAddress(overrides?: CallOverrides): Promise<string>;

  getCurrentFeePercentage(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getCurrentProjectVaultFeePercentage(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getFeeRecieverAddress(overrides?: CallOverrides): Promise<string>;

  getProjectVaultAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getBlackHoleAddress(overrides?: CallOverrides): Promise<string>;

    getCurrentFeePercentage(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getCurrentProjectVaultFeePercentage(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getFeeRecieverAddress(overrides?: CallOverrides): Promise<string>;

    getProjectVaultAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getBlackHoleAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentProjectVaultFeePercentage(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeeRecieverAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getProjectVaultAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getBlackHoleAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentFeePercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentProjectVaultFeePercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeeRecieverAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProjectVaultAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
