/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TreasuryFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createNewTreasury(address)": FunctionFragment;
    "getCurrentFeePercentage()": FunctionFragment;
    "getCurrentProjectTreasuryFeePercentage()": FunctionFragment;
    "getProjectTreasuryAddress()": FunctionFragment;
    "listManagedTreasuries()": FunctionFragment;
    "managedTreasuries(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setProjectTreasuryAddress(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateFeePercentage(uint256,uint256)": FunctionFragment;
    "updateProjectTreasuryFeePercentage(uint256,uint256)": FunctionFragment;
    "withdrawOwnerERC20(address)": FunctionFragment;
    "withdrawOwnerETH()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createNewTreasury",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentProjectTreasuryFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectTreasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listManagedTreasuries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "managedTreasuries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProjectTreasuryAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeePercentage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectTreasuryFeePercentage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawOwnerERC20",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawOwnerETH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createNewTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentProjectTreasuryFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listManagedTreasuries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "managedTreasuries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProjectTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectTreasuryFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawOwnerERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawOwnerETH",
    data: BytesLike
  ): Result;

  events: {
    "FeeUpdated(uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TreasuryCreated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FeeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TreasuryCreated"): EventFragment;
}

export type FeeUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber] & {
    updatedFeePercentage: BigNumber;
    feeBaseValue: BigNumber;
  }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type TreasuryCreatedEvent = TypedEvent<
  [string, string] & { newTreasuryAddress: string; tokenAddress: string }
>;

export class TreasuryFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TreasuryFactoryInterface;

  functions: {
    createNewTreasury(
      tokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCurrentFeePercentage(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getCurrentProjectTreasuryFeePercentage(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getProjectTreasuryAddress(overrides?: CallOverrides): Promise<[string]>;

    listManagedTreasuries(overrides?: CallOverrides): Promise<[string[]]>;

    managedTreasuries(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProjectTreasuryAddress(
      treasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateFeePercentage(
      newFeePercentage: BigNumberish,
      newBase: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectTreasuryFeePercentage(
      newFeePercentage: BigNumberish,
      newBase: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawOwnerERC20(
      erc20TokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawOwnerETH(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createNewTreasury(
    tokenAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCurrentFeePercentage(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getCurrentProjectTreasuryFeePercentage(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getProjectTreasuryAddress(overrides?: CallOverrides): Promise<string>;

  listManagedTreasuries(overrides?: CallOverrides): Promise<string[]>;

  managedTreasuries(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProjectTreasuryAddress(
    treasuryAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateFeePercentage(
    newFeePercentage: BigNumberish,
    newBase: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectTreasuryFeePercentage(
    newFeePercentage: BigNumberish,
    newBase: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawOwnerERC20(
    erc20TokenAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawOwnerETH(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createNewTreasury(
      tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getCurrentFeePercentage(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getCurrentProjectTreasuryFeePercentage(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getProjectTreasuryAddress(overrides?: CallOverrides): Promise<string>;

    listManagedTreasuries(overrides?: CallOverrides): Promise<string[]>;

    managedTreasuries(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setProjectTreasuryAddress(
      treasuryAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFeePercentage(
      newFeePercentage: BigNumberish,
      newBase: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectTreasuryFeePercentage(
      newFeePercentage: BigNumberish,
      newBase: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawOwnerERC20(
      erc20TokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawOwnerETH(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "FeeUpdated(uint256,uint256)"(
      updatedFeePercentage?: null,
      feeBaseValue?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { updatedFeePercentage: BigNumber; feeBaseValue: BigNumber }
    >;

    FeeUpdated(
      updatedFeePercentage?: null,
      feeBaseValue?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { updatedFeePercentage: BigNumber; feeBaseValue: BigNumber }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "TreasuryCreated(address,address)"(
      newTreasuryAddress?: string | null,
      tokenAddress?: string | null
    ): TypedEventFilter<
      [string, string],
      { newTreasuryAddress: string; tokenAddress: string }
    >;

    TreasuryCreated(
      newTreasuryAddress?: string | null,
      tokenAddress?: string | null
    ): TypedEventFilter<
      [string, string],
      { newTreasuryAddress: string; tokenAddress: string }
    >;
  };

  estimateGas: {
    createNewTreasury(
      tokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCurrentFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentProjectTreasuryFeePercentage(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProjectTreasuryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    listManagedTreasuries(overrides?: CallOverrides): Promise<BigNumber>;

    managedTreasuries(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProjectTreasuryAddress(
      treasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateFeePercentage(
      newFeePercentage: BigNumberish,
      newBase: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectTreasuryFeePercentage(
      newFeePercentage: BigNumberish,
      newBase: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawOwnerERC20(
      erc20TokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawOwnerETH(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createNewTreasury(
      tokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCurrentFeePercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentProjectTreasuryFeePercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProjectTreasuryAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listManagedTreasuries(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    managedTreasuries(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProjectTreasuryAddress(
      treasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateFeePercentage(
      newFeePercentage: BigNumberish,
      newBase: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectTreasuryFeePercentage(
      newFeePercentage: BigNumberish,
      newBase: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawOwnerERC20(
      erc20TokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawOwnerETH(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
